### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by Toricane** [Ralenze/bcjca#11]
As of now, the SEO of the website is lacking.
These are the tasks that need to be completed:

- [ ] Add `<meta>` tags to the `<head>`
- [ ] Organize content layout more
- [ ] Add alt text to images
- [ ] Improve site loading time
- [x] Submit sitemap to search engines

**Comment by LukeNK** [comment]
I am not sure if you want to add any other SEO meta tags, but I added tags that are recommended by Google [from here](https://developers.google.com/search/docs/crawling-indexing/special-tags). I also added `sitemap.txt` that followed [Google sitemap text format](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap#autositemap), and believe that most of the other search engines like [Bing](https://www.bing.com/webmasters/help/Sitemaps-3b5cf6ed) and DuckDuckGo import from Google, so I don't bother with those much.

**Comment by LukeNK** [comment]
Sorry mouse slip (even when not playing chess bruh).
